// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой EngineApp Tamerlan I.V.
//     Изменения в этом файле могут привести к неправильной работе
//     и будут потеряны в случае повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dashboard.Infrastructure.DataAccess.Contexts.Voting.Configuration
{
    /// <summary>
    /// Конфигурация таблицы Votings.
    /// </summary>
    internal class VotingConfiguration : IEntityTypeConfiguration<Domain.Votings.Voting>
    {
        public void Configure(EntityTypeBuilder<Domain.Votings.Voting> builder)
        {
            builder.ToTable(nameof(Domain.Votings.Voting));

            builder.HasKey(p => p.Id);
            builder.Property(p => p.Id).ValueGeneratedOnAdd();
        }
    }
}


