version: '3.7'

services:
    # api:
        # container_name: dashboard-tamerlan-api
        # build:
          # context: .
          # dockerfile: src/Dashboard/Hosts/Dashboard.Api/Dockerfile
        # ports:
          # - 5000:80
        # environment:
          # - ConnectionStrings__PostgresBoardDb=Server=postgres;Database=Board;Username=postgres;Password=password;Port=5432
        # networks:
          # - bridge
  #  depends_on:
  #    - "migrator"
    postgres:
        container_name: postgres
        # restart: always
        image: postgres
        environment:
            POSTGRES_DB: "board"
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - pg-data:/var/lib/postgresql/data
#            - /pg-data:/var/lib/postgresql/data
#            - pg-data:/var/lib/postgresql/data
#            - /mnt/pg-data:/var/lib/postgresql/data
#            - /e/my_project/docker/pg-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - bridge
#        healthcheck:
#            test: ["CMD-SHELL", "pg_isready -U twpguser -d twdb"]
#            interval: 15s
#            timeout: 10s
#            retries: 7
#            start_period: 12s
#        restart: unless-stopped
#        deploy:
#            resources:
#                limits:
#                    cpus: '1'
#                    memory: 4GB
    

    pgadmin-compose:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "postgres@domain.com"
            PGADMIN_DEFAULT_PASSWORD: "postgres"
        ports:
            - "16543:80"
        depends_on:
           - postgres
        networks:
            - bridge
            
volumes:
    pg-data:

networks:
    bridge:    
        
    