// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой EngineApp Tamerlan I.V.
//     Изменения в этом файле могут привести к неправильной работе
//     и будут потеряны в случае повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------

using Engine.Contracts.Base;

namespace Dashboard.Contracts.Feedback
{
    /// <summary>
    /// Сущность отзывов.
    /// </summary>
    public class UpdateFeedbackDto : BaseDto
    {
        /// <summary>
        /// Описание.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Рейтинг.
        /// </summary>
        public int Rating { get; set; }
    }
}
