// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой EngineApp Tamerlan I.V.
//     Изменения в этом файле могут привести к неправильной работе
//     и будут потеряны в случае повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------

using Dashboard.Domain.Products;

namespace Dashboard.Application.AppServices.Contexts.Product.Repositories

{
/// <summary>
/// Репозиторий для работы с товарами.
/// </summary>
public interface IProductRepository
{
    /// <summary>
    /// Возвращает Товар по идентификатору.
    /// </summary>
    /// <param name="id">Идентификатор Товара.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Модель Товара <see cref="Domain.Products.Product"/></returns>
    Task<Domain.Products.Product> GetByIdAsync(Guid id, CancellationToken cancellationToken);

    /// <summary>
    /// Возвращает список -- Товара.
    /// </summary>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Список моделей Товара <see cref="Domain.Products.Product"/></returns>
    IQueryable < Domain.Products.Product > GetAllAsync(CancellationToken cancellationToken);

    /// <summary>
    /// Возвращает список -- Товара, постранично в зависимости от размера страницы и индекса страницы.
    /// </summary>
    /// <param name="id">Идентификатор Товара.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <param name="pageSize">Размер страницы.</param>
    /// <param name="pageIndex">Номер страницы.</param>
    /// <returns>Список моделей -- Товара <see cref="Domain.Products.Product"/></returns>
    //IQueryable < Domain.Products.Product > GetPageAsync(int pageSize, int pageIndex, CancellationToken cancellationToken);

    /// <summary>
    /// Создает Товар по модели.
    /// </summary>
    /// <param name="model">Модель Товара.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Идентификатор созданной сущности</returns>
    Task<Guid> CreateAsync(Domain.Products.Product model, CancellationToken cancellationToken);

    /// <summary>
    /// Обновляет(изменяет) Товар по модели.
    /// </summary>
    /// <param name="model">Модель Товара.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Модель Товара <see cref="Domain.Products.Product"/></returns>
    Task<Domain.Products.Product> UpdateAsync(Domain.Products.Product model, CancellationToken cancellationToken);

    /// <summary>
    /// Удаляет Товар по модели.
    /// </summary>
    /// <param name="id">Идентификатор Товара.</param>
    /// <param name="model">Модель Товара.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Идентификатор удаленного Товара</returns>
    Task<Guid> DeleteAsync(Domain.Products.Product model, CancellationToken cancellationToken);
}
}

