// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой EngineApp Tamerlan I.V.
//     Изменения в этом файле могут привести к неправильной работе
//     и будут потеряны в случае повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dashboard.Infrastructure.DataAccess.Contexts.Community.Configuration
{
    /// <summary>
    /// Конфигурация таблицы Communitys.
    /// </summary>
    internal class CommunityConfiguration : IEntityTypeConfiguration<Domain.Communitys.Community>
    {
        public void Configure(EntityTypeBuilder<Domain.Communitys.Community> builder)
        {
            builder.ToTable(nameof(Domain.Communitys.Community));

            builder.HasKey(p => p.Id);
            builder.Property(p => p.Id).ValueGeneratedOnAdd();
        }
    }
}


