// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой EngineApp Tamerlan I.V.
//     Изменения в этом файле могут привести к неправильной работе
//     и будут потеряны в случае повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------

using Dashboard.Domain.Feedbacks;

namespace Dashboard.Application.AppServices.Contexts.Feedback.Repositories

{
/// <summary>
/// Репозиторий для работы с отзывами.
/// </summary>
public interface IFeedbackRepository
{
    /// <summary>
    /// Возвращает Отзыв по идентификатору.
    /// </summary>
    /// <param name="id">Идентификатор Отзыва.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Модель Отзыва <see cref="Domain.Feedbacks.Feedback"/></returns>
    Task<Domain.Feedbacks.Feedback> GetByIdAsync(Guid id, CancellationToken cancellationToken);

    /// <summary>
    /// Возвращает список -- Отзыва.
    /// </summary>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Список моделей Отзыва <see cref="Domain.Feedbacks.Feedback"/></returns>
    IQueryable < Domain.Feedbacks.Feedback > GetAllAsync(CancellationToken cancellationToken);

    /// <summary>
    /// Возвращает список -- Отзыва, постранично в зависимости от размера страницы и индекса страницы.
    /// </summary>
    /// <param name="id">Идентификатор Отзыва.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <param name="pageSize">Размер страницы.</param>
    /// <param name="pageIndex">Номер страницы.</param>
    /// <returns>Список моделей -- Отзыва <see cref="Domain.Feedbacks.Feedback"/></returns>
    //IQueryable < Domain.Feedbacks.Feedback > GetPageAsync(int pageSize, int pageIndex, CancellationToken cancellationToken);

    /// <summary>
    /// Создает Отзыв по модели.
    /// </summary>
    /// <param name="model">Модель Отзыва.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Идентификатор созданной сущности</returns>
    Task<Guid> CreateAsync(Domain.Feedbacks.Feedback model, CancellationToken cancellationToken);

    /// <summary>
    /// Обновляет(изменяет) Отзыв по модели.
    /// </summary>
    /// <param name="model">Модель Отзыва.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Модель Отзыва <see cref="Domain.Feedbacks.Feedback"/></returns>
    Task<Domain.Feedbacks.Feedback> UpdateAsync(Domain.Feedbacks.Feedback model, CancellationToken cancellationToken);

    /// <summary>
    /// Удаляет Отзыв по модели.
    /// </summary>
    /// <param name="id">Идентификатор Отзыва.</param>
    /// <param name="model">Модель Отзыва.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Идентификатор удаленного Отзыва</returns>
    Task<Guid> DeleteAsync(Domain.Feedbacks.Feedback model, CancellationToken cancellationToken);
}
}

