// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой EngineApp Tamerlan I.V.
//     Изменения в этом файле могут привести к неправильной работе
//     и будут потеряны в случае повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------

using Dashboard.Contracts.Voting;

namespace Dashboard.Application.AppServices.Contexts.Voting.Services

{
/// <summary>
/// Сервис работы с голосованиями.
/// </summary>
public interface IVotingService
{
    /// <summary>
    /// Возвращает Голосование по идентификатору.
    /// </summary>
    /// <param name="id">Идентификатор Голосования.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Модель Голосования <see cref="Domain.Votings.Voting"/></returns>
    Task<Domain.Votings.Voting> GetByIdAsync(Guid id, CancellationToken cancellationToken);

    /// <summary>
    /// Возвращает список -- Голосования.
    /// </summary>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Список моделей Голосования <see cref="VotingDto"/></returns>
    Task<VotingDto[]> GetAllAsync(CancellationToken cancellationToken);

    /// <summary>
    /// Возвращает список -- Голосования, постранично в зависимости от размера страницы и индекса страницы.
    /// </summary>
    /// <param name="id">Идентификатор Голосования.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <param name="pageSize">Размер страницы.</param>
    /// <param name="pageIndex">Номер страницы.</param>
    /// <returns>Список моделей -- Голосования <see cref="VotingDto"/></returns>
    Task<VotingDto[]> GetPageAsync(int pageSize, int pageIndex, CancellationToken cancellationToken);

    /// <summary>
    /// Создает Голосование по модели.
    /// </summary>
    /// <param name="model">Модель Голосования.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Идентификатор созданной сущности</returns>
    Task<Guid> CreateAsync(CreateVotingDto model, CancellationToken cancellationToken);

    /// <summary>
    /// Обновляет(изменяет) Голосование по модели.
    /// </summary>
    /// <param name="model">Модель Голосования.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Модель Голосования <see cref="Domain.Votings.Voting"/></returns>
    Task<Domain.Votings.Voting> UpdateAsync(UpdateVotingDto model, CancellationToken cancellationToken);

    /// <summary>
    /// Удаляет Голосование по модели.
    /// </summary>
    /// <param name="id">Идентификатор Голосования.</param>
    /// <param name="model">Модель Голосования.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Идентификатор удаленного Голосования</returns>
    Task<Guid> DeleteAsync(Guid id, CancellationToken cancellationToken);
}
}

