// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой EngineApp Tamerlan I.V.
//     Изменения в этом файле могут привести к неправильной работе
//     и будут потеряны в случае повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------

using Engine.Contracts.Base;

namespace Dashboard.Contracts.Bidding
{
    /// <summary>
    /// Сущность ПредложенияТоргов.
    /// </summary>
    public class CreateBiddingDto: BaseDto
    {
        /// <summary>
        /// Автор объявления.
        /// </summary>
        public Guid AuthorId { get; set; }

        /// <summary>
        /// Идентификатор поста.
        /// </summary>
        public Guid PostId { get; set; }

        /// <summary>
        /// Цена.
        /// </summary>
        public decimal Price { get; set; }

        /// <summary>
        /// Дата создания.
        /// </summary>
        public DateTime DateCreated { get; set; }

        /// <summary>
        /// Текст комментария.
        /// </summary>
        public string TextComment { get; set; }

    }
}
