// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой EngineApp Tamerlan I.V.
//     Изменения в этом файле могут привести к неправильной работе
//     и будут потеряны в случае повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------

using Engine.Contracts.Base;

namespace Dashboard.Contracts.Post
{
    /// <summary>
    /// Сущность ПредложенияТоргов.
    /// </summary>
    public class UpdatePostDto : BaseDto
    {
        /// <summary>
        /// Текст комментария.
        /// </summary>
        public string TextComment { get; set; }

    }
}
