// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой EngineApp Tamerlan I.V.
//     Изменения в этом файле могут привести к неправильной работе
//     и будут потеряны в случае повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dashboard.Infrastructure.DataAccess.Contexts.Feedback.Configuration
{
    /// <summary>
    /// Конфигурация таблицы Feedbacks.
    /// </summary>
    internal class PostConfiguration : IEntityTypeConfiguration<Domain.Feedbacks.Feedback>
    {
        public void Configure(EntityTypeBuilder<Domain.Feedbacks.Feedback> builder)
        {
            builder.ToTable(nameof(Domain.Feedbacks.Feedback));

            builder.HasKey(p => p.Id);
            builder.Property(p => p.Id).ValueGeneratedOnAdd();
        }
    }
}


