// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой EngineApp Tamerlan I.V.
//     Изменения в этом файле могут привести к неправильной работе
//     и будут потеряны в случае повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------

using Engine.Contracts.Base;

namespace Dashboard.Contracts.Comment
{
    /// <summary>
    /// Ккомментарий.
    /// </summary>
    public class CommentDto : BaseDto
    {
        /// <summary>
        /// Текст комментария.
        /// </summary>
        public string TextComment { get; set; }
        /// <summary>
        /// Автор объявления.
        /// </summary>
        public Guid AuthorId { get; set; }
        /// <summary>
        /// Дата создания комментария.
        /// </summary>
        public DateTime DateCreate { get; set; }
        /// <summary>
        /// Идентификатор поста.
        /// </summary>
        public Guid PostId { get; set; }
    }
}