// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Версия среды выполнения: 17.0.0.0
//  
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Engine.Application.AppServices.Structure.Repositories
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class GenIStructureRepositories : GenIStructureRepositoriesBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой EngineApp Tamerlan I.V.
//     Изменения в этом файле могут привести к неправильной работе
//     и будут потеряны в случае повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------

using Dashboard.");
            
            #line 15 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelUsing));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 15 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name1));
            
            #line default
            #line hidden
            
            #line 15 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelUsingS));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nnamespace Dashboard.Application.AppServices.Contexts.");
            
            #line 17 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name1));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 17 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeGenMulti));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n{\r\n/// <summary>\r\n/// ");
            
            #line 21 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HelpClass));
            
            #line default
            #line hidden
            this.Write("\r\n/// </summary>\r\npublic interface I");
            
            #line 23 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name1));
            
            #line default
            #line hidden
            
            #line 23 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeGen));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    /// <summary>\r\n    /// Возвращает ");
            
            #line 26 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HelpName));
            
            #line default
            #line hidden
            this.Write(" по идентификатору.\r\n    /// </summary>\r\n    /// <param name=\"id\">Идентификатор ");
            
            #line 28 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HelpName2));
            
            #line default
            #line hidden
            this.Write(".</param>\r\n    /// <param name=\"cancellationToken\">Отмена операции.</param>\r\n    " +
                    "/// <returns>Модель ");
            
            #line 30 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HelpName2));
            
            #line default
            #line hidden
            this.Write(" <see cref=\"");
            
            #line 30 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelDomain));
            
            #line default
            #line hidden
            this.Write("\"/></returns>\r\n    Task<");
            
            #line 31 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelDomain));
            
            #line default
            #line hidden
            this.Write("> GetByIdAsync(Guid id, CancellationToken cancellationToken);\r\n\r\n    /// <summary" +
                    ">\r\n    /// Возвращает список -- ");
            
            #line 34 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HelpName2));
            
            #line default
            #line hidden
            this.Write(".\r\n    /// </summary>\r\n    /// <param name=\"cancellationToken\">Отмена операции.</" +
                    "param>\r\n    /// <returns>Список моделей ");
            
            #line 37 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HelpName2));
            
            #line default
            #line hidden
            this.Write(" <see cref=\"");
            
            #line 37 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelService));
            
            #line default
            #line hidden
            this.Write("\"/></returns>\r\n    ");
            
            #line 38 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeList));
            
            #line default
            #line hidden
            this.Write(" GetAllAsync(CancellationToken cancellationToken);\r\n\r\n    /// <summary>\r\n    /// " +
                    "Возвращает список -- ");
            
            #line 41 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HelpName2));
            
            #line default
            #line hidden
            this.Write(", постранично в зависимости от размера страницы и индекса страницы.\r\n    /// </su" +
                    "mmary>\r\n    /// <param name=\"id\">Идентификатор ");
            
            #line 43 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HelpName2));
            
            #line default
            #line hidden
            this.Write(".</param>\r\n    /// <param name=\"cancellationToken\">Отмена операции.</param>\r\n    " +
                    "/// <param name=\"pageSize\">Размер страницы.</param>\r\n    /// <param name=\"pageIn" +
                    "dex\">Номер страницы.</param>\r\n    /// <returns>Список моделей -- ");
            
            #line 47 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HelpName2));
            
            #line default
            #line hidden
            this.Write(" <see cref=\"");
            
            #line 47 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelService));
            
            #line default
            #line hidden
            this.Write("\"/></returns>\r\n    ");
            
            #line 48 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ToComment));
            
            #line default
            #line hidden
            
            #line 48 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeList));
            
            #line default
            #line hidden
            this.Write(" GetPageAsync(int pageSize, int pageIndex, CancellationToken cancellationToken);\r" +
                    "\n\r\n    /// <summary>\r\n    /// Создает ");
            
            #line 51 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HelpName));
            
            #line default
            #line hidden
            this.Write(" по модели.\r\n    /// </summary>\r\n    /// <param name=\"model\">Модель ");
            
            #line 53 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HelpName2));
            
            #line default
            #line hidden
            this.Write(".</param>\r\n    /// <param name=\"cancellationToken\">Отмена операции.</param>\r\n    " +
                    "/// <returns>Идентификатор созданной сущности</returns>\r\n    Task<Guid> CreateAs" +
                    "ync(");
            
            #line 56 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelCreate));
            
            #line default
            #line hidden
            this.Write(" model, CancellationToken cancellationToken);\r\n\r\n    /// <summary>\r\n    /// Обнов" +
                    "ляет(изменяет) ");
            
            #line 59 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HelpName));
            
            #line default
            #line hidden
            this.Write(" по модели.\r\n    /// </summary>\r\n    /// <param name=\"model\">Модель ");
            
            #line 61 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HelpName2));
            
            #line default
            #line hidden
            this.Write(".</param>\r\n    /// <param name=\"cancellationToken\">Отмена операции.</param>\r\n    " +
                    "/// <returns>Модель ");
            
            #line 63 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HelpName2));
            
            #line default
            #line hidden
            this.Write(" <see cref=\"");
            
            #line 63 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelDomain));
            
            #line default
            #line hidden
            this.Write("\"/></returns>\r\n    Task<");
            
            #line 64 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelDomain));
            
            #line default
            #line hidden
            this.Write("> UpdateAsync(");
            
            #line 64 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelUpdate));
            
            #line default
            #line hidden
            this.Write(" model, CancellationToken cancellationToken);\r\n\r\n    /// <summary>\r\n    /// Удаля" +
                    "ет ");
            
            #line 67 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HelpName));
            
            #line default
            #line hidden
            this.Write(" по модели.\r\n    /// </summary>\r\n    /// <param name=\"id\">Идентификатор ");
            
            #line 69 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HelpName2));
            
            #line default
            #line hidden
            this.Write(".</param>\r\n    /// <param name=\"model\">Модель ");
            
            #line 70 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HelpName2));
            
            #line default
            #line hidden
            this.Write(".</param>\r\n    /// <param name=\"cancellationToken\">Отмена операции.</param>\r\n    " +
                    "/// <returns>Идентификатор удаленного ");
            
            #line 72 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(HelpName2));
            
            #line default
            #line hidden
            this.Write("</returns>\r\n    Task<Guid> DeleteAsync(");
            
            #line 73 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelDelete));
            
            #line default
            #line hidden
            this.Write(", CancellationToken cancellationToken);\r\n}\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 77 "E:\my_project\repos_net\Dashboard_my\TamerlanDashboard\src\Engine\Application\Engine.Application.AppServices\Structure\Repositories\GenIStructureRepositories.tt"
 
    public string Name1 { get; set; } // Post
    public string ModelUsing { get; set; } // Domain OR Contracts
    public string ModelUsingS { get; set; } // ""s"
    public string ModelDomain { get; set; } // Domain.Posts.Post
    public string ModelService { get; set; } // Domain.Posts.Post
    public string ModelCreate { get; set; } // Domain.Posts.Post
    public string ModelUpdate { get; set; } // Domain.Posts.Post
    public string ModelDelete { get; set; } // Domain.Posts.Post
    public string TypeGen { get; set; } // Repository OR Service
    public string TypeGenMulti { get; set; } // Repositories OR Services
    public string GetTypeList { get; set; } // IQueryable<Domain.Posts.Post> OR Task<PostDto[]>

    public string HelpClass { get; set; } // Репозиторий для работы с объявлениями.
    
    public string ToComment { get; set; } // закомментировать

    public string HelpName { get; set; } // Что? Объявление
    public string HelpName2 { get; set; } // Модель чего? Объявления



        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class GenIStructureRepositoriesBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
