// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой EngineApp Tamerlan I.V.
//     Изменения в этом файле могут привести к неправильной работе
//     и будут потеряны в случае повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------

using Dashboard.Domain.Posts;

namespace Dashboard.Application.AppServices.Contexts.Post.Repositories

{
/// <summary>
/// Репозиторий для работы с объявлениями.
/// </summary>
public interface IPostRepository
{
    /// <summary>
    /// Возвращает Объявление по идентификатору.
    /// </summary>
    /// <param name="id">Идентификатор Объявления.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Модель Объявления <see cref="Domain.Posts.Post"/></returns>
    Task<Domain.Posts.Post> GetByIdAsync(Guid id, CancellationToken cancellationToken);

    /// <summary>
    /// Возвращает список -- Объявления.
    /// </summary>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Список моделей Объявления <see cref="Domain.Posts.Post"/></returns>
    IQueryable < Domain.Posts.Post > GetAllAsync(CancellationToken cancellationToken);

    /// <summary>
    /// Возвращает список -- Объявления, постранично в зависимости от размера страницы и индекса страницы.
    /// </summary>
    /// <param name="id">Идентификатор Объявления.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <param name="pageSize">Размер страницы.</param>
    /// <param name="pageIndex">Номер страницы.</param>
    /// <returns>Список моделей -- Объявления <see cref="Domain.Posts.Post"/></returns>
    //IQueryable < Domain.Posts.Post > GetPageAsync(int pageSize, int pageIndex, CancellationToken cancellationToken);

    /// <summary>
    /// Создает Объявление по модели.
    /// </summary>
    /// <param name="model">Модель Объявления.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Идентификатор созданной сущности</returns>
    Task<Guid> CreateAsync(Domain.Posts.Post model, CancellationToken cancellationToken);

    /// <summary>
    /// Обновляет(изменяет) Объявление по модели.
    /// </summary>
    /// <param name="model">Модель Объявления.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Модель Объявления <see cref="Domain.Posts.Post"/></returns>
    Task<Domain.Posts.Post> UpdateAsync(Domain.Posts.Post model, CancellationToken cancellationToken);

    /// <summary>
    /// Удаляет Объявление по модели.
    /// </summary>
    /// <param name="id">Идентификатор Объявления.</param>
    /// <param name="model">Модель Объявления.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Идентификатор удаленного Объявления</returns>
    Task<Guid> DeleteAsync(Domain.Posts.Post model, CancellationToken cancellationToken);
}
}

