// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой EngineApp Tamerlan I.V.
//     Изменения в этом файле могут привести к неправильной работе
//     и будут потеряны в случае повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------

using Dashboard.Application.AppServices.Contexts.Bookmark.Repositories;
using Dashboard.Contracts;
using Dashboard.Contracts.Bookmark;
using Dashboard.Infrastructure.Repository;
using System.Linq.Expressions;
using System;
using Microsoft.EntityFrameworkCore;

namespace Dashboard.Infrastructure.DataAccess.Contexts.Bookmark.Repositories;

/// <inheritdoc cref="IBookmarkRepository"/>
public class BookmarkRepository : IBookmarkRepository
{
    private readonly IRepository<Domain.Bookmarks.Bookmark> _repository;

    /// <inheritdoc />
    public BookmarkRepository(IRepository<Domain.Bookmarks.Bookmark> repository)
    {
        _repository = repository;
    }

    /// <inheritdoc />
    public async Task<Guid> CreateAsync(Domain.Bookmarks.Bookmark model, CancellationToken cancellationToken)
    {
        /*await*/ _repository.AddAsync(model);
        return model.Id;
    }

    /// <inheritdoc />
    public Task<Domain.Bookmarks.Bookmark> GetByIdAsync(Guid id, CancellationToken cancellationToken)
    {
        return _repository.GetByIdAsync(id, cancellationToken);
    }

    /// <inheritdoc />
    public IQueryable<Domain.Bookmarks.Bookmark> GetAllAsync(CancellationToken cancellationToken)
    {
        return _repository.GetAll();
    }

    /// <inheritdoc />
    public async Task<Domain.Bookmarks.Bookmark> UpdateAsync(Domain.Bookmarks.Bookmark model, CancellationToken cancellationToken)
    {
        /*await*/ _repository.UpdateAsync(model);
        return model;
    }

    /// <inheritdoc />
    public async Task<Guid> DeleteAsync(Domain.Bookmarks.Bookmark model, CancellationToken cancellationToken)
    {
        /*await*/ _repository.DeleteAsync(model);
        return model.Id;
    }
}


