// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой EngineApp Tamerlan I.V.
//     Изменения в этом файле могут привести к неправильной работе
//     и будут потеряны в случае повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------

using Engine.Contracts.Base;

namespace Dashboard.Contracts.History
{
    /// <summary>
    /// Сущность истории просмотра продукта.
    /// </summary>
    public class HistoryDto : BaseDto
    {
        /// <summary>
        /// Автор объявления.
        /// </summary>
        public Guid AuthorId { get; set; }

        /// <summary>
        /// Родительский объект.
        /// </summary>
        public Guid ParrentId { get; set; }

        /// <summary>
        /// Дата создания.
        /// </summary>
        public DateTime DateCreated { get; set; }

    }
}
