// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой EngineApp Tamerlan I.V.
//     Изменения в этом файле могут привести к неправильной работе
//     и будут потеряны в случае повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------

using Dashboard.Contracts.Post;

namespace Dashboard.Application.AppServices.Contexts.Post.Services

{
/// <summary>
/// Сервис работы с объявлениями.
/// </summary>
public interface IPostService
{
    /// <summary>
    /// Возвращает Объявление по идентификатору.
    /// </summary>
    /// <param name="id">Идентификатор Объявления.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Модель Объявления <see cref="Domain.Posts.Post"/></returns>
    Task<Domain.Posts.Post> GetByIdAsync(Guid id, CancellationToken cancellationToken);

    /// <summary>
    /// Возвращает список -- Объявления.
    /// </summary>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Список моделей Объявления <see cref="PostDto"/></returns>
    Task<PostDto[]> GetAllAsync(CancellationToken cancellationToken);

    /// <summary>
    /// Возвращает список -- Объявления, постранично в зависимости от размера страницы и индекса страницы.
    /// </summary>
    /// <param name="id">Идентификатор Объявления.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <param name="pageSize">Размер страницы.</param>
    /// <param name="pageIndex">Номер страницы.</param>
    /// <returns>Список моделей -- Объявления <see cref="PostDto"/></returns>
    Task<PostDto[]> GetPageAsync(int pageSize, int pageIndex, CancellationToken cancellationToken);

    /// <summary>
    /// Создает Объявление по модели.
    /// </summary>
    /// <param name="model">Модель Объявления.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Идентификатор созданной сущности</returns>
    Task<Guid> CreateAsync(CreatePostDto model, CancellationToken cancellationToken);

    /// <summary>
    /// Обновляет(изменяет) Объявление по модели.
    /// </summary>
    /// <param name="model">Модель Объявления.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Модель Объявления <see cref="Domain.Posts.Post"/></returns>
    Task<Domain.Posts.Post> UpdateAsync(UpdatePostDto model, CancellationToken cancellationToken);

    /// <summary>
    /// Удаляет Объявление по модели.
    /// </summary>
    /// <param name="id">Идентификатор Объявления.</param>
    /// <param name="model">Модель Объявления.</param>
    /// <param name="cancellationToken">Отмена операции.</param>
    /// <returns>Идентификатор удаленного Объявления</returns>
    Task<Guid> DeleteAsync(Guid id, CancellationToken cancellationToken);
}
}

