// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой EngineApp Tamerlan I.V.
//     Изменения в этом файле могут привести к неправильной работе
//     и будут потеряны в случае повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------

using Dashboard.Application.AppServices.Contexts.History.Repositories;
using Dashboard.Contracts;
using Dashboard.Contracts.History;
using Dashboard.Infrastructure.Repository;
using System.Linq.Expressions;
using System;
using Microsoft.EntityFrameworkCore;

namespace Dashboard.Infrastructure.DataAccess.Contexts.History.Repositories;

/// <inheritdoc cref="IHistoryRepository"/>
public class HistoryRepository : IHistoryRepository
{
    private readonly IRepository<Domain.Historys.History> _repository;

    /// <inheritdoc />
    public HistoryRepository(IRepository<Domain.Historys.History> repository)
    {
        _repository = repository;
    }

    /// <inheritdoc />
    public async Task<Guid> CreateAsync(Domain.Historys.History model, CancellationToken cancellationToken)
    {
        await _repository.AddAsync(model);
        return model.Id;
    }

    /// <inheritdoc />
    public Task<Domain.Historys.History> GetByIdAsync(Guid id, CancellationToken cancellationToken)
    {
        return _repository.GetByIdAsync(id, cancellationToken);
    }

    /// <inheritdoc />
    public IQueryable<Domain.Historys.History> GetAllAsync(CancellationToken cancellationToken)
    {
        return _repository.GetAll();
    }

    /// <inheritdoc />
    public async Task<Domain.Historys.History> UpdateAsync(Domain.Historys.History model, CancellationToken cancellationToken)
    {
        await _repository.UpdateAsync(model);
        return model;
    }

    /// <inheritdoc />
    public async Task<Guid> DeleteAsync(Domain.Historys.History model, CancellationToken cancellationToken)
    {
        await _repository.DeleteAsync(model);
        return model.Id;
    }
}


