// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой EngineApp Tamerlan I.V.
//     Изменения в этом файле могут привести к неправильной работе
//     и будут потеряны в случае повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dashboard.Infrastructure.DataAccess.Contexts.Bidding.Configuration
{
    /// <summary>
    /// Конфигурация таблицы Biddings.
    /// </summary>
    internal class BiddingConfiguration : IEntityTypeConfiguration<Domain.Biddings.Bidding>
    {
        public void Configure(EntityTypeBuilder<Domain.Biddings.Bidding> builder)
        {
            builder.ToTable(nameof(Domain.Biddings.Bidding));

            builder.HasKey(p => p.Id);
            builder.Property(p => p.Id).ValueGeneratedOnAdd();
        }
    }
}


