// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой EngineApp Tamerlan I.V.
//     Изменения в этом файле могут привести к неправильной работе
//     и будут потеряны в случае повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------

using Engine.Contracts.Base;

namespace Dashboard.Contracts.User
{
    /// <summary>
    /// Сущность пользователя.
    /// </summary>
    public class UpdateUserDto : BaseDto
    {
        /// <summary>
        /// Логин.
        /// </summary>
        public string Login { get; set; }
        /// <summary>
        /// Регистрационный Email.
        /// </summary>
        public string EmailReg { get; set; }
        /// <summary>
        /// Телефон.
        /// </summary>
        public string Phone { get; set; }
    }
}